# Generated by Django 2.1.5 on 2019-02-10 12:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp')),
                ('want_to_judge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Debate')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state_team', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('easters_attend', models.BooleanField(default=False)),
                ('easters_break', models.BooleanField(default=False)),
                ('australs_break', models.BooleanField(default=False)),
                ('awdc_break', models.BooleanField(default=False)),
                ('wudc_break', models.BooleanField(default=False)),
                ('judge_qualification_score', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('judged_before', models.BooleanField(default=False)),
                ('wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Team'),
        ),
        migrations.AddField(
            model_name='score',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Speaker'),
        ),
        migrations.AddField(
            model_name='debate',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Speaker'),
        ),
        migrations.AddField(
            model_name='debate',
            name='winning_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Team'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='debate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Debate'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='speakers',
            field=models.ManyToManyField(to='baseapp.Speaker'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Team'),
        ),
    ]
