# Generated by Django 2.1.5 on 2019-01-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('state_team', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('easters_attend', models.BooleanField(default=False)),
                ('easters_break', models.BooleanField(default=False)),
                ('australs_break', models.BooleanField(default=False)),
                ('awdc_break', models.BooleanField(default=False)),
                ('wudc_break', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('judged_before', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Team'),
        ),
    ]
