# Generated by Django 2.1.5 on 2019-01-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='Debate',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='match',
            new_name='debate',
        ),
    ]
