# Generated by Django 2.1.5 on 2019-01-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='speakers',
            field=models.ManyToManyField(limit_choices_to={'team': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Team')}, to='fixtures.Speaker'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Team'),
        ),
    ]
