# Generated by Django 2.1.5 on 2019-02-13 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20190213_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='debate',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='match_day',
        ),
        migrations.AddField(
            model_name='debate',
            name='attendance1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance1_debate', to='baseapp.Attendance'),
        ),
        migrations.AddField(
            model_name='debate',
            name='attendance2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance2_debate', to='baseapp.Attendance'),
        ),
        migrations.AddField(
            model_name='debate',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 22, 40, 35, 718466)),
        ),
        migrations.DeleteModel(
            name='MatchDay',
        ),
    ]
