# Generated by Django 2.1.5 on 2019-01-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_auto_20190113_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Team'),
        ),
    ]
