# Generated by Django 2.1.5 on 2019-02-13 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20190213_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
