# Generated by Django 2.1.5 on 2019-01-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20190123_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Team'),
        ),
    ]
