# Generated by Django 2.1.5 on 2019-01-15 12:01

from django.db import migrations, models
import fixtures.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_auto_20190113_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='speakers',
            field=models.ManyToManyField(to='fixtures.Speaker'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(default=fixtures.models._local_time_now, verbose_name='timestamp'),
        ),
    ]
