# Generated by Django 2.1.5 on 2019-01-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20190126_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='winning_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('speaker', 'debate')},
        ),
    ]
