# Generated by Django 2.1.5 on 2019-02-15 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20190215_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='timestamp'),
        ),
    ]
