# Generated by Django 2.1.5 on 2019-01-18 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_auto_20190115_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendances', models.ManyToManyField(to='fixtures.Attendance')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Match')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Speaker')),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Team'),
        ),
    ]
