# Generated by Django 2.1.5 on 2019-01-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20190128_0157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
    ]
