# Generated by Django 2.1.5 on 2019-01-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20190128_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='attendance1',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='attendance2',
        ),
        migrations.AddField(
            model_name='attendance',
            name='debate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Debate'),
        ),
    ]
