# Generated by Django 2.1.7 on 2019-02-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20190216_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='want_to_judge',
            field=models.BooleanField(default=False, verbose_name='prefer to judge'),
        ),
    ]
