# Generated by Django 2.1.5 on 2019-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_auto_20190203_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='judge_qualification_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
