# Generated by Django 2.1.5 on 2019-02-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_speaker_judge_qualification_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='judge_qualification_score',
            field=models.IntegerField(default=0),
        ),
    ]
