# Generated by Django 2.1.7 on 2019-02-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_speaker_vetoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='vetoes',
            field=models.ManyToManyField(to='baseapp.Speaker'),
        ),
    ]
