# Generated by Django 2.1.5 on 2019-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_auto_20190203_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='want_to_judge',
            field=models.BooleanField(default=False),
        ),
    ]
