# Generated by Django 2.1.7 on 2019-02-16 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_auto_20190216_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
    ]
