# Generated by Django 2.1.7 on 2019-02-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_matchday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='date',
        ),
        migrations.AddField(
            model_name='debate',
            name='match_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.MatchDay'),
        ),
    ]
