# Generated by Django 2.1.5 on 2019-02-10 08:35

import baseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_auto_20190203_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='time_generated',
            field=models.DateTimeField(default=baseapp.models._local_time_now, editable=False),
        ),
    ]
