# Generated by Django 2.1.5 on 2019-02-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_debate_time_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='time_generated',
        ),
    ]
