# Generated by Django 2.1.7 on 2019-02-16 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_auto_20190216_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
    ]
