# Generated by Django 2.1.7 on 2019-02-17 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0018_auto_20190217_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
