# Generated by Django 2.1.7 on 2019-02-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0021_auto_20190217_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='attendance1',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='attendance2',
        ),
        migrations.AddField(
            model_name='debate',
            name='affirmative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debates_affirmative', to='baseapp.Attendance', verbose_name='Affirmative team'),
        ),
        migrations.AddField(
            model_name='debate',
            name='negative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debates_negative', to='baseapp.Attendance', verbose_name='Negative team'),
        ),
    ]
