# Generated by Django 2.1.7 on 2019-02-27 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0023_auto_20190223_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='vetoes',
        ),
        migrations.AddField(
            model_name='speaker',
            name='high_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='judge_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='low_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veto',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetoes_initiated', to='baseapp.Speaker'),
        ),
        migrations.AddField(
            model_name='veto',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetoes_received', to='baseapp.Speaker'),
        ),
    ]
