# Generated by Django 2.1.7 on 2019-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0024_auto_20190227_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='veto',
            name='affected_debates',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
