# Generated by Django 2.1.7 on 2019-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0025_veto_affected_debates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veto',
            name='affected_debates',
            field=models.IntegerField(default=0),
        ),
    ]
