# Generated by Django 2.1.7 on 2019-03-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0028_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='match_day',
        ),
        migrations.AddField(
            model_name='debate',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Room'),
        ),
    ]
