# Generated by Django 2.1.7 on 2019-03-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0029_auto_20190321_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='low_qualified',
            new_name='mini_break',
        ),
    ]
