# Generated by Django 2.1.5 on 2019-01-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('want_to_judge', models.BooleanField(default=True)),
                ('speakers', models.ManyToManyField(to='fixtures.Speaker')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Team')),
            ],
        ),
    ]
